"""MessagingGateway (D15): the bot depends on this interface only, never on a specific BSP, so the provider behind it
can change (Meta Cloud API until ADR 0008; Evolution API — bot/evolution.py — since)."""
from __future__ import annotations

from typing import Protocol


class GatewayError(RuntimeError):
    pass


class MessagingGateway(Protocol):
    async def send_text(self, to: str, body: str) -> str: ...
    async def send_buttons(self, to: str, body: str, buttons: list[tuple[str, str]]) -> str: ...
    async def send_list(self, to: str, body: str, button: str, rows: list[tuple[str, str, str]]) -> str: ...
    async def send_template(self, to: str, name: str, params: list[str], quick_reply_payload: str | None = None) -> str: ...
    async def download_media(self, media_id: str) -> tuple[bytes, str]: ...
    async def send_document(self, to: str, filename: str, data: bytes, mime: str, caption: str = "") -> str: ...
    # Best-effort humanization (ADR 0008 addendum): unlike every method above, these two must NEVER raise GatewayError —
    # a broken "typing..." indicator or reaction must never block the real reply from being sent.
    async def send_presence(self, to: str, composing: bool, delay_ms: int = 1200) -> None: ...
    async def react(self, to: str, message_id: str, emoji: str) -> None: ...
